/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author mendo
 */
public class GestionEstudiante extends javax.swing.JFrame {

  /**
   * Creates new form StudentManagement
   */
  public GestionEstudiante() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtNameLastname = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        TabbedPanel = new javax.swing.JTabbedPane();
        panelActividad = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        CheckDone = new javax.swing.JCheckBox();
        txtTitulo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAreaDetalle = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        btnModificarActividad = new javax.swing.JButton();
        btnLimpiarActividad = new javax.swing.JButton();
        btnSubirActividad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        jSeparator13 = new javax.swing.JSeparator();
        errComentario1 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbUnidad2 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbUnidad3 = new javax.swing.JTable();
        jSeparator11 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbUnidad1 = new javax.swing.JTable();
        jSeparator5 = new javax.swing.JSeparator();
        toggBtnCalculoVectorial1 = new javax.swing.JToggleButton();
        toggBtnProgramacion1 = new javax.swing.JToggleButton();
        toggBtnQuimica1 = new javax.swing.JToggleButton();
        toggBtnFisica1 = new javax.swing.JToggleButton();
        jSeparator12 = new javax.swing.JSeparator();
        errMateria = new javax.swing.JLabel();
        panelCalificacion = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        toggBtnFisica = new javax.swing.JToggleButton();
        toggBtnQuimica = new javax.swing.JToggleButton();
        toggBtnCalculoVectorial = new javax.swing.JToggleButton();
        toggBtnProgramacion = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        boxUnidad = new javax.swing.JComboBox<>();
        btnFiltro = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbCalificaiones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtActividadDato = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JLabel();
        txtPonderacion = new javax.swing.JLabel();
        txtRetroalimentacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPorcentaje = new javax.swing.JLabel();
        boxActividades = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        errActividad = new javax.swing.JLabel();
        errUnidad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtUnidadDato = new javax.swing.JLabel();
        txtPromedioCurso = new javax.swing.JLabel();
        errAsignatura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameLastname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNameLastname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNameLastname.setText("Name LastName");
        jPanel1.add(txtNameLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 300, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfil-User.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 80, 70));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("BANNER");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 360, 40));

        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRefrescar.png"))); // NOI18N
        btnRefrescar.setText("Recargar");
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtEmail.setText("email");
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 300, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCerrar.png"))); // NOI18N
        btnSalir.setText("Cerrar Sesion");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        panelActividad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setBorder(javax.swing.BorderFactory.createTitledBorder("Marcar como :"));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 110, 50));

        CheckDone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CheckDone.setText("Hecha");
        CheckDone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(CheckDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, 20));

        txtTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Título :"));
        jPanel2.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 40));

        txtAreaDetalle.setColumns(20);
        txtAreaDetalle.setRows(5);
        jScrollPane5.setViewportView(txtAreaDetalle);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 295, 70));

        jSeparator7.setBorder(javax.swing.BorderFactory.createTitledBorder("Comentario :"));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 314, 100));

        btnModificarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEditar.png"))); // NOI18N
        btnModificarActividad.setText("Editar");
        jPanel2.add(btnModificarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 90, 40));

        btnLimpiarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnLimpiar.png"))); // NOI18N
        btnLimpiarActividad.setText("Limpiar");
        btnLimpiarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActividadActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 90, 40));

        btnSubirActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnSubir.png"))); // NOI18N
        btnSubirActividad.setText("Subir");
        btnSubirActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActividadActionPerformed(evt);
            }
        });
        jPanel2.add(btnSubirActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, 40));

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 290, 60));

        jSeparator13.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle :"));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 314, 100));

        errComentario1.setForeground(new java.awt.Color(255, 0, 0));
        errComentario1.setText("errComentario");
        jPanel2.add(errComentario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 290, -1));

        panelActividad.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 330, 370));

        jSeparator10.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidad 2 :"));
        panelActividad.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 540, 150));

        tbUnidad2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tbUnidad2);

        panelActividad.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 520, 120));

        tbUnidad3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane9.setViewportView(tbUnidad3);

        panelActividad.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, 520, 120));

        jSeparator11.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidad 3 :"));
        panelActividad.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 540, 150));

        tbUnidad1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tbUnidad1);

        panelActividad.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 520, 120));

        jSeparator5.setBorder(javax.swing.BorderFactory.createTitledBorder("Unidad 1 :"));
        panelActividad.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 540, 150));

        toggBtnCalculoVectorial1.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnCalculoVectorial1);
        toggBtnCalculoVectorial1.setText("Cálculo Vectorial");
        toggBtnCalculoVectorial1.setBorder(null);
        toggBtnCalculoVectorial1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelActividad.add(toggBtnCalculoVectorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 130, 20));

        toggBtnProgramacion1.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnProgramacion1);
        toggBtnProgramacion1.setText("Programación");
        toggBtnProgramacion1.setBorder(null);
        toggBtnProgramacion1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelActividad.add(toggBtnProgramacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 130, 20));

        toggBtnQuimica1.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnQuimica1);
        toggBtnQuimica1.setText("Química");
        toggBtnQuimica1.setBorder(null);
        toggBtnQuimica1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelActividad.add(toggBtnQuimica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 20));

        toggBtnFisica1.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnFisica1);
        toggBtnFisica1.setText("Física");
        toggBtnFisica1.setBorder(null);
        toggBtnFisica1.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelActividad.add(toggBtnFisica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 20));

        jSeparator12.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del curso"));
        panelActividad.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 100));

        errMateria.setForeground(new java.awt.Color(255, 0, 0));
        errMateria.setText("errMateria");
        panelActividad.add(errMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 290, -1));

        TabbedPanel.addTab("Actividades", panelActividad);

        panelCalificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre del curso"));
        panelCalificacion.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 60));

        toggBtnFisica.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnFisica);
        toggBtnFisica.setText("Física");
        toggBtnFisica.setBorder(null);
        toggBtnFisica.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelCalificacion.add(toggBtnFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 20));

        toggBtnQuimica.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnQuimica);
        toggBtnQuimica.setText("Química");
        toggBtnQuimica.setBorder(null);
        toggBtnQuimica.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelCalificacion.add(toggBtnQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 140, 20));

        toggBtnCalculoVectorial.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnCalculoVectorial);
        toggBtnCalculoVectorial.setText("Cálculo Vectorial");
        toggBtnCalculoVectorial.setBorder(null);
        toggBtnCalculoVectorial.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelCalificacion.add(toggBtnCalculoVectorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 140, 20));

        toggBtnProgramacion.setBackground(new java.awt.Color(204, 204, 255));
        btnGroup.add(toggBtnProgramacion);
        toggBtnProgramacion.setText("Programación");
        toggBtnProgramacion.setBorder(null);
        toggBtnProgramacion.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        panelCalificacion.add(toggBtnProgramacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 140, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Calificaciones :"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Unidad 1", "Unidad 2", "Unidad 3" }));
        jPanel3.add(boxUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 200, -1));

        btnFiltro.setText("Filtrar");
        jPanel3.add(btnFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 110, 40));

        jLabel5.setText("Unidad :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, 20));

        tbCalificaiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Actividad", "Ponderación", "Calificación", "Porcentaje", "Retroalimentación"
            }
        ));
        jScrollPane6.setViewportView(tbCalificaiones);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 830, 290));

        jLabel1.setText("%");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 30, 40));

        jLabel2.setText("Cálculo total ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 20));

        txtActividadDato.setText("Actividad");
        jPanel3.add(txtActividadDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 100, 20));

        txtCalificacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtCalificacion.setText("00.00");
        jPanel3.add(txtCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 140, 40));

        txtPonderacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPonderacion.setText("00.00");
        jPanel3.add(txtPonderacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 80, 40));

        txtRetroalimentacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(txtRetroalimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 160, 40));

        jLabel6.setText("%");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 30, 40));

        txtPorcentaje.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtPorcentaje.setText("00.00");
        jPanel3.add(txtPorcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 120, 40));

        boxActividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Tarea", "Taller", "Laboratorio", "Prueba", "Examen" }));
        jPanel3.add(boxActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 220, -1));

        jLabel4.setText("Actividades :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 80, 20));

        errActividad.setText("errActividad");
        jPanel3.add(errActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 220, 20));

        errUnidad.setText("errUnidad");
        jPanel3.add(errUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 200, -1));

        jLabel7.setText("Total");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 40, 20));

        txtUnidadDato.setText("Unidad #");
        jPanel3.add(txtUnidadDato, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 60, 20));

        panelCalificacion.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 850, 420));

        txtPromedioCurso.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPromedioCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPromedioCurso.setText("00.00");
        txtPromedioCurso.setBorder(javax.swing.BorderFactory.createTitledBorder("Promedio de asignatura : "));
        panelCalificacion.add(txtPromedioCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 190, 60));

        errAsignatura.setText("errAsignatura");
        panelCalificacion.add(errAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 610, -1));

        TabbedPanel.addTab("Calidicaciones", panelCalificacion);

        jPanel1.add(TabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 870, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActividadActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActividadActionPerformed

    private void btnSubirActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActividadActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_btnSubirActividadActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(GestionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(GestionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(GestionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(GestionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new GestionEstudiante().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox CheckDone;
    public javax.swing.JTabbedPane TabbedPanel;
    public javax.swing.JComboBox<String> boxActividades;
    public javax.swing.JComboBox<String> boxUnidad;
    public javax.swing.JButton btnFiltro;
    public javax.swing.ButtonGroup btnGroup;
    public javax.swing.JButton btnLimpiarActividad;
    public javax.swing.JButton btnModificarActividad;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSubirActividad;
    public javax.swing.JLabel errActividad;
    public javax.swing.JLabel errAsignatura;
    public javax.swing.JLabel errComentario1;
    public javax.swing.JLabel errMateria;
    public javax.swing.JLabel errUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JPanel panelActividad;
    public javax.swing.JPanel panelCalificacion;
    public javax.swing.JTable tbCalificaiones;
    public javax.swing.JTable tbUnidad1;
    public javax.swing.JTable tbUnidad2;
    public javax.swing.JTable tbUnidad3;
    public javax.swing.JToggleButton toggBtnCalculoVectorial;
    public javax.swing.JToggleButton toggBtnCalculoVectorial1;
    public javax.swing.JToggleButton toggBtnFisica;
    public javax.swing.JToggleButton toggBtnFisica1;
    public javax.swing.JToggleButton toggBtnProgramacion;
    public javax.swing.JToggleButton toggBtnProgramacion1;
    public javax.swing.JToggleButton toggBtnQuimica;
    public javax.swing.JToggleButton toggBtnQuimica1;
    public javax.swing.JLabel txtActividadDato;
    public javax.swing.JTextArea txtAreaDetalle;
    private javax.swing.JLabel txtCalificacion;
    public javax.swing.JTextArea txtComentario;
    public javax.swing.JLabel txtEmail;
    public javax.swing.JLabel txtNameLastname;
    private javax.swing.JLabel txtPonderacion;
    private javax.swing.JLabel txtPorcentaje;
    public javax.swing.JLabel txtPromedioCurso;
    private javax.swing.JLabel txtRetroalimentacion;
    public javax.swing.JLabel txtTitulo;
    public javax.swing.JLabel txtUnidadDato;
    // End of variables declaration//GEN-END:variables
}
