/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author mendo
 */
public class GestionDocente extends javax.swing.JFrame {

    /**
     * Creates new form StudentManagement
     */
    public GestionDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtNameLastnameDocen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtMateriaDocen = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JButton();
        txtEmailDocen = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnCargarJson = new javax.swing.JButton();
        TabbedPanel = new javax.swing.JTabbedPane();
        panelActividad = new javax.swing.JPanel();
        boxUnidadActividad = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        boxActividades = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreActividad = new javax.swing.JTextField();
        errNombreActividad = new javax.swing.JLabel();
        errUnidadActividad = new javax.swing.JLabel();
        errActividad = new javax.swing.JLabel();
        errDetalleActividad = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetalleActividad = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        spnPonderacionActividad = new javax.swing.JSpinner();
        errPonderacionActividad = new javax.swing.JLabel();
        btnSubirActividad = new javax.swing.JButton();
        btnEliminarActividad = new javax.swing.JButton();
        btnBuscarActividad = new javax.swing.JButton();
        btnModificarActividad = new javax.swing.JButton();
        btnLimpiarActividad = new javax.swing.JButton();
        panelActiviades = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbActiviades = new javax.swing.JTable();
        panelCalificacion = new javax.swing.JPanel();
        boxUnidadCalificacion = new javax.swing.JComboBox<>();
        errUnidadCalificacion = new javax.swing.JLabel();
        btnFiltroCalificacion = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spnCalificacion = new javax.swing.JSpinner();
        errEstado = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtObservacionCalificacion = new javax.swing.JTextArea();
        errObservacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkEstadoNo = new javax.swing.JCheckBox();
        checkEstadoSi = new javax.swing.JCheckBox();
        errCalifiCalificacion1 = new javax.swing.JLabel();
        btnEliminarCalificaciones = new javax.swing.JButton();
        btnBuscarCalificaciones = new javax.swing.JButton();
        btnModificarCalificaciones = new javax.swing.JButton();
        btnLimpiarCalificaciones = new javax.swing.JButton();
        panelStudent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameLastnameDocen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNameLastnameDocen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtNameLastnameDocen.setText("Name LastName");
        jPanel1.add(txtNameLastnameDocen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 300, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Perfil-User.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 80, 80));

        txtMateriaDocen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtMateriaDocen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtMateriaDocen.setText("materia");
        jPanel1.add(txtMateriaDocen, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 300, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel10.setText("BANNER");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 400, 80));

        btnRefrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRefrescar.png"))); // NOI18N
        btnRefrescar.setText("Recargar");
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        txtEmailDocen.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEmailDocen.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtEmailDocen.setText("email");
        jPanel1.add(txtEmailDocen, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 300, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCerrar.png"))); // NOI18N
        btnSalir.setText("Cerrar Sesion");
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, -1, -1));

        btnCargarJson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnImportarDatos.png"))); // NOI18N
        btnCargarJson.setText("Import. Estudiantes");
        jPanel1.add(btnCargarJson, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        panelActividad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxUnidadActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Unidad 1", "Unidad 2", "Unidad 3" }));
        panelActividad.add(boxUnidadActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 120, -1));

        jLabel1.setText("Unidad :");
        panelActividad.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, 20));

        boxActividades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Tarea", "Taller", "Laboratorio", "Prueba", "Examen" }));
        panelActividad.add(boxActividades, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, -1));

        jLabel2.setText("Actividades :");
        panelActividad.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 20));

        jLabel3.setText("Nombre :");
        panelActividad.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));
        panelActividad.add(txtNombreActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 250, -1));

        errNombreActividad.setText("errNombreActividad");
        panelActividad.add(errNombreActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 260, -1));

        errUnidadActividad.setText("errUnidadActividad");
        panelActividad.add(errUnidadActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 260, 20));

        errActividad.setText("errActividad");
        panelActividad.add(errActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 260, 20));

        errDetalleActividad.setText("errDetalleActividad");
        panelActividad.add(errDetalleActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 260, -1));

        txtDetalleActividad.setColumns(20);
        txtDetalleActividad.setRows(5);
        jScrollPane2.setViewportView(txtDetalleActividad);

        jScrollPane3.setViewportView(jScrollPane2);

        panelActividad.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 250, 70));

        jLabel11.setText("Detalle :");
        panelActividad.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 70, -1));

        jLabel12.setText("Ponderación :");
        panelActividad.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, -1));
        panelActividad.add(spnPonderacionActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 70, -1));

        errPonderacionActividad.setText("errPonderacionActividad");
        panelActividad.add(errPonderacionActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 290, -1));

        btnSubirActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnSubir.png"))); // NOI18N
        btnSubirActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActividadActionPerformed(evt);
            }
        });
        panelActividad.add(btnSubirActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 60, 40));

        btnEliminarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEliminar.png"))); // NOI18N
        panelActividad.add(btnEliminarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 60, 40));

        btnBuscarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnBuscar.png"))); // NOI18N
        btnBuscarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActividadActionPerformed(evt);
            }
        });
        panelActividad.add(btnBuscarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 60, 40));

        btnModificarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEditar.png"))); // NOI18N
        panelActividad.add(btnModificarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 60, 40));

        btnLimpiarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnLimpiar.png"))); // NOI18N
        btnLimpiarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActividadActionPerformed(evt);
            }
        });
        panelActividad.add(btnLimpiarActividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 60, 40));

        panelActiviades.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Activiades", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbActiviades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbActiviades);

        javax.swing.GroupLayout panelActiviadesLayout = new javax.swing.GroupLayout(panelActiviades);
        panelActiviades.setLayout(panelActiviadesLayout);
        panelActiviadesLayout.setHorizontalGroup(
            panelActiviadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActiviadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelActiviadesLayout.setVerticalGroup(
            panelActiviadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActiviadesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelActividad.add(panelActiviades, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 500, -1));

        TabbedPanel.addTab("Actividad", panelActividad);

        panelCalificacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boxUnidadCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Unidad 1", "Unidad 2", "Unidad 3" }));
        panelCalificacion.add(boxUnidadCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, -1));

        errUnidadCalificacion.setText("errUnidad");
        panelCalificacion.add(errUnidadCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, -1));

        btnFiltroCalificacion.setText("Filtrar");
        panelCalificacion.add(btnFiltroCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 80, -1));

        jLabel5.setText("Unidad :");
        panelCalificacion.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, 20));
        panelCalificacion.add(spnCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 100, -1));

        errEstado.setText("errEstado");
        panelCalificacion.add(errEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, -1));

        jLabel7.setText("Actividad Hecha :");
        panelCalificacion.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        txtObservacionCalificacion.setColumns(20);
        txtObservacionCalificacion.setRows(5);
        jScrollPane4.setViewportView(txtObservacionCalificacion);

        panelCalificacion.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 180, 80));

        errObservacion.setText("errObservacion");
        panelCalificacion.add(errObservacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 180, -1));

        jLabel6.setText("Observación :");
        panelCalificacion.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 80, 20));

        jLabel13.setText("Calificación :");
        panelCalificacion.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 80, 20));

        checkEstadoNo.setText("No");
        panelCalificacion.add(checkEstadoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        checkEstadoSi.setText("Si");
        panelCalificacion.add(checkEstadoSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        errCalifiCalificacion1.setText("errCalifiCalificacion");
        panelCalificacion.add(errCalifiCalificacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 180, -1));

        btnEliminarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEliminar.png"))); // NOI18N
        btnEliminarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCalificacionesActionPerformed(evt);
            }
        });
        panelCalificacion.add(btnEliminarCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 60, 40));

        btnBuscarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnBuscar.png"))); // NOI18N
        btnBuscarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCalificacionesActionPerformed(evt);
            }
        });
        panelCalificacion.add(btnBuscarCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 60, 40));

        btnModificarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnEditar.png"))); // NOI18N
        panelCalificacion.add(btnModificarCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 60, 40));

        btnLimpiarCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnLimpiar.png"))); // NOI18N
        btnLimpiarCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCalificacionesActionPerformed(evt);
            }
        });
        panelCalificacion.add(btnLimpiarCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 60, 40));

        panelStudent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudiantes :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbStudent);

        javax.swing.GroupLayout panelStudentLayout = new javax.swing.GroupLayout(panelStudent);
        panelStudent.setLayout(panelStudentLayout);
        panelStudentLayout.setHorizontalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelStudentLayout.setVerticalGroup(
            panelStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCalificacion.add(panelStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 580, -1));

        TabbedPanel.addTab("Calificar", panelCalificacion);

        jPanel1.add(TabbedPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 880, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCalificacionesActionPerformed

    private void btnLimpiarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCalificacionesActionPerformed

    private void btnLimpiarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActividadActionPerformed

    private void btnBuscarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActividadActionPerformed

    private void btnSubirActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubirActividadActionPerformed

    private void btnEliminarCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCalificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane TabbedPanel;
    public javax.swing.JComboBox<String> boxActividades;
    public javax.swing.JComboBox<String> boxUnidadActividad;
    public javax.swing.JComboBox<String> boxUnidadCalificacion;
    public javax.swing.JButton btnBuscarActividad;
    public javax.swing.JButton btnBuscarCalificaciones;
    public javax.swing.JButton btnCargarJson;
    public javax.swing.JButton btnEliminarActividad;
    public javax.swing.JButton btnEliminarCalificaciones;
    public javax.swing.JButton btnFiltroCalificacion;
    private javax.swing.ButtonGroup btnGroup;
    public javax.swing.JButton btnLimpiarActividad;
    public javax.swing.JButton btnLimpiarCalificaciones;
    public javax.swing.JButton btnModificarActividad;
    public javax.swing.JButton btnModificarCalificaciones;
    public javax.swing.JButton btnRefrescar;
    public javax.swing.JButton btnSalir;
    public javax.swing.JButton btnSubirActividad;
    public javax.swing.JCheckBox checkEstadoNo;
    public javax.swing.JCheckBox checkEstadoSi;
    public javax.swing.JLabel errActividad;
    public javax.swing.JLabel errCalifiCalificacion1;
    public javax.swing.JLabel errDetalleActividad;
    public javax.swing.JLabel errEstado;
    public javax.swing.JLabel errNombreActividad;
    public javax.swing.JLabel errObservacion;
    public javax.swing.JLabel errPonderacionActividad;
    public javax.swing.JLabel errUnidadActividad;
    public javax.swing.JLabel errUnidadCalificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JPanel panelActiviades;
    public javax.swing.JPanel panelActividad;
    public javax.swing.JPanel panelCalificacion;
    public javax.swing.JPanel panelStudent;
    public javax.swing.JSpinner spnCalificacion;
    public javax.swing.JSpinner spnPonderacionActividad;
    public javax.swing.JTable tbActiviades;
    public javax.swing.JTable tbStudent;
    public javax.swing.JTextArea txtDetalleActividad;
    public javax.swing.JLabel txtEmailDocen;
    public javax.swing.JLabel txtMateriaDocen;
    public javax.swing.JLabel txtNameLastnameDocen;
    public javax.swing.JTextField txtNombreActividad;
    public javax.swing.JTextArea txtObservacionCalificacion;
    // End of variables declaration//GEN-END:variables
}
