/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author mendo
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form StudentManagement
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        errPassword = new javax.swing.JLabel();
        errUserName1 = new javax.swing.JLabel();
        btnSession = new javax.swing.JButton();
        btnRecuperar = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        panelPas = new javax.swing.JPanel();
        icoPasw = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        panelUserName = new javax.swing.JPanel();
        txtUserName = new javax.swing.JTextField();
        icoUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MOODLE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 70));

        errPassword.setForeground(new java.awt.Color(153, 153, 153));
        errPassword.setText("errPassword");
        jPanel1.add(errPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 210, 20));

        errUserName1.setForeground(new java.awt.Color(153, 153, 153));
        errUserName1.setText("errUserName");
        jPanel1.add(errUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, 20));

        btnSession.setBackground(new java.awt.Color(51, 153, 255));
        btnSession.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSession.setForeground(new java.awt.Color(255, 255, 255));
        btnSession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/brnIniciarSesion.png"))); // NOI18N
        btnSession.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSessionActionPerformed(evt);
            }
        });
        jPanel1.add(btnSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 50, 40));

        btnRecuperar.setText("¿Olvidó su contraseña o usuario?");
        btnRecuperar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 230, 220, -1));

        btnSignUp.setBackground(new java.awt.Color(51, 153, 255));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("REGISTER");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 210, 30));

        panelPas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelPas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icoPasw.setBackground(new java.awt.Color(51, 153, 255));
        icoPasw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoPasw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-pasword.png"))); // NOI18N
        icoPasw.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelPas.add(icoPasw, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setBorder(null);
        panelPas.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        jPanel1.add(panelPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, 40));

        panelUserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelUserName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setBorder(null);
        txtUserName.setCaretColor(new java.awt.Color(51, 153, 255));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        panelUserName.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 170, 40));

        icoUser.setBackground(new java.awt.Color(51, 153, 255));
        icoUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono-perfilUser.png"))); // NOI18N
        icoUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelUserName.add(icoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(panelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniciar-sesion.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 70, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoLogin.gif"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSessionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSessionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSessionActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRecuperarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRecuperar;
    public javax.swing.JButton btnSession;
    public javax.swing.JButton btnSignUp;
    public javax.swing.JLabel errPassword;
    public javax.swing.JLabel errUserName1;
    public javax.swing.JLabel icoPasw;
    public javax.swing.JLabel icoUser;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel panelPas;
    public javax.swing.JPanel panelUserName;
    public javax.swing.JTextField txtPassword;
    public javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
