/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author mendo
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form newRegistration
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        calenFechaNaci = new com.toedter.calendar.JCalendar();
        txtLastName = new javax.swing.JTextField();
        txtCI = new javax.swing.JTextField();
        panelMaterias = new javax.swing.JPanel();
        radFisica = new javax.swing.JRadioButton();
        radCalculoVec = new javax.swing.JRadioButton();
        errMaterias = new javax.swing.JLabel();
        radProgramacion = new javax.swing.JRadioButton();
        radQuimica = new javax.swing.JRadioButton();
        errName = new javax.swing.JLabel();
        errLastName = new javax.swing.JLabel();
        errCedula = new javax.swing.JLabel();
        errDate = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        boxTipo = new javax.swing.JComboBox<>();
        errTipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(51, 153, 255));
        txtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 200, -1));
        jPanel1.add(calenFechaNaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 260, 120));

        txtLastName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLastName.setForeground(new java.awt.Color(51, 153, 255));
        txtLastName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 200, -1));

        txtCI.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtCI.setForeground(new java.awt.Color(51, 153, 255));
        txtCI.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "C.I  :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.add(txtCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 200, -1));

        panelMaterias.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materias: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        panelMaterias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radFisica.setForeground(new java.awt.Color(51, 153, 255));
        radFisica.setText("Física");
        panelMaterias.add(radFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        radCalculoVec.setForeground(new java.awt.Color(51, 153, 255));
        radCalculoVec.setText("Cálculo Vectorial");
        panelMaterias.add(radCalculoVec, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        errMaterias.setForeground(new java.awt.Color(51, 153, 255));
        errMaterias.setText("errTipo");
        panelMaterias.add(errMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 380, 19));

        radProgramacion.setForeground(new java.awt.Color(51, 153, 255));
        radProgramacion.setText("Programación");
        panelMaterias.add(radProgramacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        radQuimica.setForeground(new java.awt.Color(51, 153, 255));
        radQuimica.setText("Química");
        radQuimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radQuimicaActionPerformed(evt);
            }
        });
        panelMaterias.add(radQuimica, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jPanel1.add(panelMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 420, 120));

        errName.setForeground(new java.awt.Color(51, 153, 255));
        errName.setText("errName");
        jPanel1.add(errName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 200, -1));

        errLastName.setForeground(new java.awt.Color(51, 153, 255));
        errLastName.setText("errLastName");
        jPanel1.add(errLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 200, -1));

        errCedula.setForeground(new java.awt.Color(51, 153, 255));
        errCedula.setText("errCedula");
        jPanel1.add(errCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 200, -1));

        errDate.setForeground(new java.awt.Color(51, 153, 255));
        errDate.setText("errDate");
        jPanel1.add(errDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 260, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 135)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 153, 255));
        jLabel6.setText("REGISTER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 640, 130));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAgregarUsuario.png"))); // NOI18N
        btnRegister.setText("REGISTRARSE");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 280, 40));

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnQuitarUsuario.png"))); // NOI18N
        btnCancel.setText("CANCELAR");
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 280, 40));

        boxTipo.setForeground(new java.awt.Color(51, 153, 255));
        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Docente", "Estudiante" }));
        boxTipo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.add(boxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 200, -1));

        errTipo.setForeground(new java.awt.Color(51, 153, 255));
        errTipo.setText("errMateria");
        jPanel1.add(errTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registro-User.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 140));

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Nacimento :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 300, 170));

        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 450, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radQuimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radQuimicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radQuimicaActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> boxTipo;
    public javax.swing.JButton btnCancel;
    public javax.swing.ButtonGroup btnGroup;
    public javax.swing.JButton btnRegister;
    public com.toedter.calendar.JCalendar calenFechaNaci;
    public javax.swing.JLabel errCedula;
    public javax.swing.JLabel errDate;
    public javax.swing.JLabel errLastName;
    public javax.swing.JLabel errMaterias;
    public javax.swing.JLabel errName;
    public javax.swing.JLabel errTipo;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JPanel panelMaterias;
    public javax.swing.JRadioButton radCalculoVec;
    public javax.swing.JRadioButton radFisica;
    public javax.swing.JRadioButton radProgramacion;
    public javax.swing.JRadioButton radQuimica;
    public javax.swing.JTextField txtCI;
    public javax.swing.JTextField txtLastName;
    public javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
